### ISSUE TITLE
spelling error FYI

### ISSUE THREAD

**Issue by amawalke** [learn-co-curriculum/phase-0-pac-1-comparisons-in-javascript#3]
On this statement "You should prefer === and !== for comparisons. There are [a lot of rules Links to an external site.](https://dorey.github.io/JavaScript-Equality-Table/)that JavaScript follows when performing type coercion using the == operator, and it's not worth keeping track of them all." I believe the word "coercion" should be the word "conversion"? If so, wanted to let you know!

**Comment by lizbur10** [comment]
Hi @amawalke ! Actually, both words are correct. Generally, `coercion` refers to when JavaScript makes the conversion for you, based on what it thinks the code should be doing. It isn't always right, however, so it's safer to explicitly convert the type yourself. You can think of `coercion` as a more specific type of `conversion`.

Hope that helps! 💙
